// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: category.proto

package go_micro_service_category

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CategoryRequest struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryLevel        uint32   `protobuf:"varint,2,opt,name=category_level,json=categoryLevel,proto3" json:"category_level,omitempty"`
	CategoryParent       int64    `protobuf:"varint,3,opt,name=category_parent,json=categoryParent,proto3" json:"category_parent,omitempty"`
	CategoryImage        string   `protobuf:"bytes,4,opt,name=category_image,json=categoryImage,proto3" json:"category_image,omitempty"`
	CategoryDescription  string   `protobuf:"bytes,5,opt,name=category_description,json=categoryDescription,proto3" json:"category_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryRequest) Reset()         { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()    {}
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{0}
}
func (m *CategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryRequest.Unmarshal(m, b)
}
func (m *CategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryRequest.Marshal(b, m, deterministic)
}
func (m *CategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryRequest.Merge(m, src)
}
func (m *CategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryRequest.Size(m)
}
func (m *CategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryRequest proto.InternalMessageInfo

func (m *CategoryRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryRequest) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryRequest) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryRequest) GetCategoryImage() string {
	if m != nil {
		return m.CategoryImage
	}
	return ""
}

func (m *CategoryRequest) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type CreateCategoryResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CategoryId           int64    `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{1}
}
func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(m, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCategoryResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type UpdateCategoryResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{2}
}
func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteCategoryRequest struct {
	CategoryId           int64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{3}
}
func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(m, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

func (m *DeleteCategoryRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResponse) Reset()         { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()    {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{4}
}
func (m *DeleteCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResponse.Merge(m, src)
}
func (m *DeleteCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResponse.Size(m)
}
func (m *DeleteCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResponse proto.InternalMessageInfo

func (m *DeleteCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindByNameRequest struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByNameRequest) Reset()         { *m = FindByNameRequest{} }
func (m *FindByNameRequest) String() string { return proto.CompactTextString(m) }
func (*FindByNameRequest) ProtoMessage()    {}
func (*FindByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{5}
}
func (m *FindByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByNameRequest.Unmarshal(m, b)
}
func (m *FindByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByNameRequest.Marshal(b, m, deterministic)
}
func (m *FindByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByNameRequest.Merge(m, src)
}
func (m *FindByNameRequest) XXX_Size() int {
	return xxx_messageInfo_FindByNameRequest.Size(m)
}
func (m *FindByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByNameRequest proto.InternalMessageInfo

func (m *FindByNameRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type CategoryResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName         string   `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryLevel        uint32   `protobuf:"varint,3,opt,name=category_level,json=categoryLevel,proto3" json:"category_level,omitempty"`
	CategoryParent       int64    `protobuf:"varint,4,opt,name=category_parent,json=categoryParent,proto3" json:"category_parent,omitempty"`
	CategoryImages       string   `protobuf:"bytes,5,opt,name=category_images,json=categoryImages,proto3" json:"category_images,omitempty"`
	CategoryDescription  string   `protobuf:"bytes,6,opt,name=category_description,json=categoryDescription,proto3" json:"category_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryResponse) Reset()         { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()    {}
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{6}
}
func (m *CategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResponse.Unmarshal(m, b)
}
func (m *CategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResponse.Marshal(b, m, deterministic)
}
func (m *CategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResponse.Merge(m, src)
}
func (m *CategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryResponse.Size(m)
}
func (m *CategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResponse proto.InternalMessageInfo

func (m *CategoryResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CategoryResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryResponse) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryResponse) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryResponse) GetCategoryImages() string {
	if m != nil {
		return m.CategoryImages
	}
	return ""
}

func (m *CategoryResponse) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type FindByIdRequest struct {
	CategoryId           int64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{7}
}
func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(m, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type FindByLevelRequest struct {
	Level                uint32   `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByLevelRequest) Reset()         { *m = FindByLevelRequest{} }
func (m *FindByLevelRequest) String() string { return proto.CompactTextString(m) }
func (*FindByLevelRequest) ProtoMessage()    {}
func (*FindByLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{8}
}
func (m *FindByLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByLevelRequest.Unmarshal(m, b)
}
func (m *FindByLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByLevelRequest.Marshal(b, m, deterministic)
}
func (m *FindByLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByLevelRequest.Merge(m, src)
}
func (m *FindByLevelRequest) XXX_Size() int {
	return xxx_messageInfo_FindByLevelRequest.Size(m)
}
func (m *FindByLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByLevelRequest proto.InternalMessageInfo

func (m *FindByLevelRequest) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type FindByParentRequest struct {
	ParentId             int64    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByParentRequest) Reset()         { *m = FindByParentRequest{} }
func (m *FindByParentRequest) String() string { return proto.CompactTextString(m) }
func (*FindByParentRequest) ProtoMessage()    {}
func (*FindByParentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{9}
}
func (m *FindByParentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByParentRequest.Unmarshal(m, b)
}
func (m *FindByParentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByParentRequest.Marshal(b, m, deterministic)
}
func (m *FindByParentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByParentRequest.Merge(m, src)
}
func (m *FindByParentRequest) XXX_Size() int {
	return xxx_messageInfo_FindByParentRequest.Size(m)
}
func (m *FindByParentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByParentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByParentRequest proto.InternalMessageInfo

func (m *FindByParentRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type FindAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllRequest) Reset()         { *m = FindAllRequest{} }
func (m *FindAllRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllRequest) ProtoMessage()    {}
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{10}
}
func (m *FindAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllRequest.Unmarshal(m, b)
}
func (m *FindAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllRequest.Marshal(b, m, deterministic)
}
func (m *FindAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllRequest.Merge(m, src)
}
func (m *FindAllRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllRequest.Size(m)
}
func (m *FindAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllRequest proto.InternalMessageInfo

type FindAllResponse struct {
	Category             []*CategoryResponse `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindAllResponse) Reset()         { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()    {}
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{11}
}
func (m *FindAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllResponse.Unmarshal(m, b)
}
func (m *FindAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllResponse.Marshal(b, m, deterministic)
}
func (m *FindAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllResponse.Merge(m, src)
}
func (m *FindAllResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllResponse.Size(m)
}
func (m *FindAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllResponse proto.InternalMessageInfo

func (m *FindAllResponse) GetCategory() []*CategoryResponse {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*CategoryRequest)(nil), "go.micro.service.category.CategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "go.micro.service.category.CreateCategoryResponse")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "go.micro.service.category.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "go.micro.service.category.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "go.micro.service.category.DeleteCategoryResponse")
	proto.RegisterType((*FindByNameRequest)(nil), "go.micro.service.category.FindByNameRequest")
	proto.RegisterType((*CategoryResponse)(nil), "go.micro.service.category.CategoryResponse")
	proto.RegisterType((*FindByIdRequest)(nil), "go.micro.service.category.FindByIdRequest")
	proto.RegisterType((*FindByLevelRequest)(nil), "go.micro.service.category.FindByLevelRequest")
	proto.RegisterType((*FindByParentRequest)(nil), "go.micro.service.category.FindByParentRequest")
	proto.RegisterType((*FindAllRequest)(nil), "go.micro.service.category.FindAllRequest")
	proto.RegisterType((*FindAllResponse)(nil), "go.micro.service.category.FindAllResponse")
}

func init() { proto.RegisterFile("category.proto", fileDescriptor_1c6ef5ed29d8d1a1) }

var fileDescriptor_1c6ef5ed29d8d1a1 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x49, 0x3f, 0xd2, 0x29, 0x75, 0xc2, 0x36, 0x54, 0x26, 0x1c, 0x88, 0x16, 0x21,
	0x42, 0x01, 0x8b, 0x9a, 0x0b, 0x57, 0x68, 0x04, 0x8a, 0x84, 0x10, 0x32, 0xe2, 0xc2, 0xa5, 0x32,
	0xf1, 0x28, 0x32, 0x8a, 0x3f, 0xea, 0x35, 0x45, 0x3c, 0x0e, 0x6f, 0xc6, 0x3b, 0xf0, 0x02, 0xc8,
	0xbb, 0xd9, 0x75, 0x9c, 0x38, 0x8e, 0x8d, 0x7a, 0xf4, 0x7c, 0xfd, 0x66, 0x76, 0xe6, 0x9f, 0x80,
	0x31, 0x73, 0x53, 0x9c, 0x47, 0xc9, 0x2f, 0x2b, 0x4e, 0xa2, 0x34, 0xa2, 0xf7, 0xe7, 0x91, 0x15,
	0xf8, 0xb3, 0x24, 0xb2, 0x38, 0x26, 0x37, 0xfe, 0x0c, 0x2d, 0x15, 0xc0, 0xfe, 0x10, 0xe8, 0x5d,
	0x2e, 0x3f, 0x1c, 0xbc, 0xfe, 0x81, 0x3c, 0xa5, 0x8f, 0xe0, 0x44, 0xf9, 0xaf, 0x42, 0x37, 0x40,
	0x93, 0x8c, 0xc8, 0xf8, 0xc8, 0xb9, 0xa3, 0x8c, 0x1f, 0xdd, 0x00, 0xe9, 0xe3, 0x9c, 0x72, 0xb5,
	0xc0, 0x1b, 0x5c, 0x98, 0xed, 0x11, 0x19, 0x9f, 0x38, 0x3a, 0xf5, 0x43, 0x66, 0xa4, 0x4f, 0xa0,
	0xa7, 0xc3, 0x62, 0x37, 0xc1, 0x30, 0x35, 0x3b, 0x23, 0x32, 0xee, 0x38, 0x3a, 0xfb, 0x93, 0xb0,
	0x16, 0xea, 0xf9, 0x81, 0x3b, 0x47, 0x73, 0x4f, 0x50, 0x75, 0xbd, 0x69, 0x66, 0xa4, 0x17, 0x30,
	0xd0, 0x61, 0x1e, 0xf2, 0x59, 0xe2, 0xc7, 0xa9, 0x1f, 0x85, 0xe6, 0xbe, 0x08, 0x3e, 0x55, 0xbe,
	0x49, 0xee, 0x62, 0x9f, 0xe1, 0xec, 0x32, 0x41, 0x37, 0xc5, 0x7c, 0x4e, 0x1e, 0x47, 0x21, 0x47,
	0x6a, 0xc2, 0x61, 0x80, 0x9c, 0x67, 0x30, 0x39, 0xa2, 0xfa, 0xa4, 0x0f, 0xe1, 0x38, 0xef, 0xc6,
	0x13, 0xa3, 0x75, 0x1c, 0xd0, 0xad, 0x78, 0xcc, 0x86, 0xb3, 0x2f, 0xb1, 0xd7, 0xa8, 0x28, 0x7b,
	0x0d, 0xf7, 0x26, 0xb8, 0xc0, 0xd5, 0x1c, 0xf9, 0xe0, 0x6b, 0x34, 0x52, 0x46, 0x5b, 0xcf, 0xac,
	0x41, 0xbb, 0xfb, 0xce, 0x0f, 0xbd, 0xb7, 0x62, 0x5d, 0x4d, 0x56, 0xcb, 0xfe, 0x12, 0xe8, 0x6f,
	0x80, 0x0c, 0x68, 0xeb, 0xd6, 0xda, 0xbe, 0xb7, 0x59, 0xa9, 0x5d, 0xeb, 0x48, 0x3a, 0x35, 0x8f,
	0x64, 0xaf, 0xf4, 0x48, 0x56, 0x03, 0xc5, 0x91, 0xf0, 0xe5, 0xe2, 0x8d, 0xc2, 0x95, 0xf0, 0xad,
	0x67, 0x72, 0xb0, 0xfd, 0x4c, 0x6c, 0xe8, 0xc9, 0xf7, 0x9a, 0x7a, 0xb5, 0xf7, 0x72, 0x0e, 0x54,
	0xe6, 0x88, 0x39, 0x54, 0xda, 0x00, 0xf6, 0xe5, 0xb0, 0x44, 0x0c, 0x2b, 0x3f, 0x98, 0x0d, 0xa7,
	0x32, 0x56, 0xce, 0xa2, 0x82, 0x1f, 0xc0, 0x91, 0x1c, 0x39, 0x27, 0x74, 0xa5, 0x61, 0xea, 0xb1,
	0x3e, 0x18, 0x59, 0xce, 0x9b, 0x85, 0xaa, 0xcd, 0xbe, 0xca, 0x2e, 0x85, 0x65, 0xb9, 0x99, 0xf7,
	0xd0, 0x55, 0x2d, 0x99, 0x64, 0xd4, 0x19, 0x1f, 0xdb, 0xcf, 0xac, 0xad, 0x82, 0xb7, 0xd6, 0x17,
	0xeb, 0xe8, 0x64, 0xfb, 0xf7, 0x21, 0x74, 0x95, 0x9b, 0x5e, 0x83, 0x51, 0x54, 0x0d, 0x3d, 0xaf,
	0x55, 0x55, 0xb4, 0x39, 0xbc, 0xa8, 0x8a, 0x2d, 0x15, 0x23, 0x6b, 0x65, 0xc8, 0xa2, 0xa6, 0x6e,
	0x0d, 0x59, 0x2e, 0x55, 0xd6, 0xa2, 0x3f, 0xc1, 0x28, 0x0a, 0x8b, 0xbe, 0xac, 0x28, 0x53, 0xaa,
	0xde, 0x4a, 0x70, 0xb9, 0x6a, 0xc5, 0xac, 0xe2, 0x72, 0x94, 0x47, 0xaa, 0x94, 0x3e, 0xaf, 0x28,
	0xb5, 0x21, 0xe6, 0x61, 0x93, 0x35, 0xb3, 0x16, 0x0d, 0xa0, 0x5f, 0x44, 0x4e, 0x27, 0x95, 0x0f,
	0xbc, 0xa6, 0x86, 0xa6, 0xb8, 0x44, 0xde, 0x7b, 0x8e, 0x93, 0x5a, 0x7f, 0xb1, 0x93, 0xb8, 0xaa,
	0xa5, 0xe1, 0xae, 0x06, 0x57, 0x84, 0xc0, 0x5a, 0x34, 0x85, 0x41, 0x91, 0xb9, 0xfc, 0xdd, 0xb0,
	0x76, 0x42, 0x0b, 0xa2, 0x6c, 0x48, 0xfd, 0xae, 0x35, 0xa9, 0xaf, 0xe8, 0x69, 0x9d, 0x02, 0xff,
	0xc1, 0xfa, 0x76, 0x20, 0xfe, 0xd1, 0x5f, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x0a, 0xc0,
	0xef, 0xe3, 0x07, 0x00, 0x00,
}
